spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  sql:
    init:
      mode: always

lined:
  security:
    jwt:
      secret: MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=

logging:
  level:
    org.testcontainers: INFO
