spring:
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  sql:
    init:
      mode: never

lined:
  security:
    jwt:
      secret: MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
  auth:
    reset-token-secret: integration-password-reset-token-secret

logging:
  level:
    org.testcontainers: INFO
