package io.backend.lined.auth.api;

import io.backend.lined.auth.service.AuthService;
import io.backend.lined.auth.service.AuthLoginResult;
import io.backend.lined.auth.service.PasswordResetService;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.security.web.csrf.CsrfToken;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/auth")
@RequiredArgsConstructor
public class AuthController {

  private final AuthService authService;
  private final PasswordResetService passwordResetService;
  private final RefreshTokenCookieWriter refreshTokenCookieWriter;
  private final RefreshTokenCookieReader refreshTokenCookieReader;

  @PostMapping("/login")
  public AuthLoginResponseDto login(
      @Valid @RequestBody AuthLoginDto dto, HttpServletResponse response) {
    AuthLoginResult result = authService.login(dto);
    refreshTokenCookieWriter.write(response, result.refreshToken(), result.refreshTokenExpiresAt());
    return result.response();
  }

  @PostMapping("/refresh")
  public AuthLoginResponseDto refresh(HttpServletRequest request, HttpServletResponse response) {
    String refreshToken = refreshTokenCookieReader.read(request).orElse(null);
    AuthLoginResult result = authService.refresh(refreshToken);
    refreshTokenCookieWriter.write(response, result.refreshToken(), result.refreshTokenExpiresAt());
    return result.response();
  }

  /**
   * Revokes the refresh session identified by the current cookie and expires that cookie.
   *
   * @param request servlet request carrying the current refresh cookie, if present
   * @param response servlet response receiving the expired refresh cookie
   */
  @PostMapping("/logout")
  @ResponseStatus(HttpStatus.NO_CONTENT)
  public void logout(HttpServletRequest request, HttpServletResponse response) {
    authService.logout(refreshTokenCookieReader.read(request).orElse(null));
    refreshTokenCookieWriter.clear(response);
  }

  /**
   * Provides the non-secret CSRF token required by cookie-authenticated browser operations.
   *
   * @param csrfToken token generated by the configured cookie repository
   * @return token metadata for the browser request header
   */
  @GetMapping("/csrf")
  public CsrfToken csrf(CsrfToken csrfToken) {
    return csrfToken;
  }

  @PostMapping("/password-reset-requests")
  @ResponseStatus(HttpStatus.ACCEPTED)
  public void requestPasswordReset(@Valid @RequestBody PasswordResetRequestDto dto) {
    passwordResetService.requestReset(dto);
  }

  @PostMapping("/password-resets")
  @ResponseStatus(HttpStatus.NO_CONTENT)
  public void resetPassword(@Valid @RequestBody PasswordResetDto dto) {
    passwordResetService.reset(dto);
  }
}
