import com.github.spotbugs.snom.SpotBugsTask

plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.6'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'com.github.spotbugs' version '6.0.18'
    id 'checkstyle'
    id 'jacoco'
    id "org.sonarqube" version "7.2.2.6593"
}

group = 'io.backend'
version = '0.0.1-SNAPSHOT'
description = 'Lined — Where life and quality time meet.'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

jacoco {
    toolVersion = "0.8.10"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'io.micrometer:micrometer-tracing-bridge-otel'
    implementation 'io.opentelemetry:opentelemetry-exporter-otlp:1.40.0'
    implementation 'io.opentelemetry:opentelemetry-sdk-extension-autoconfigure:1.40.0'
    implementation 'org.springframework.security:spring-security-crypto:6.4.4'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.mapstruct:mapstruct:1.6.0'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.9'

    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.0'
    annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
    annotationProcessor 'org.projectlombok:lombok'

    compileOnly 'org.projectlombok:lombok'

    runtimeOnly 'org.postgresql:postgresql'
    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'

    testAnnotationProcessor 'org.mapstruct:mapstruct-processor:1.6.0'
    testAnnotationProcessor 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'com.h2database:h2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

spotbugs {
    effort = 'max'
    reportLevel = 'low'
    ignoreFailures = true
    excludeFilter = file("$rootDir/config/spotbugs/spotbugs-exclude.xml")
}

checkstyle {
    toolVersion = '10.20.0'
    configFile = file("$rootDir/config/checkstyle/checkstyle.xml")
    ignoreFailures = false
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
        html.required = true
        html.outputLocation = layout.buildDirectory.dir('reports/jacoco')
    }
}

sonar {
    properties {
        property "sonar.projectKey", "Pan14ek_lined"
        property "sonar.organization", "pan14ek"
        property "sonar.coverage.jacoco.xmlReportPaths", "build/reports/jacoco/test/jacocoTestReport.xml"
    }
}

tasks.withType(SpotBugsTask).configureEach {
    reports {
        xml.required = true
        xml.outputLocation = file("$buildDir/reports/spotbugs/${name}.xml")

        html.required = true
        html.outputLocation = file("$buildDir/reports/spotbugs/${name}.html")

        sarif.required = true
        sarif.outputLocation = file("$buildDir/reports/spotbugs/${name}.sarif")
    }
}

tasks.named("spotbugsMain", SpotBugsTask) {
    dependsOn(tasks.named("classes"))

    classes.setFrom(sourceSets.main.output)

    sourceDirs.setFrom(sourceSets.main.allSource.srcDirs)

    auxiliaryClasspath.setFrom(sourceSets.main.compileClasspath)
}

tasks.named("spotbugsTest", SpotBugsTask) {
    dependsOn(tasks.named("testClasses"))

    classes.setFrom(sourceSets.test.output)
    sourceDirs.setFrom(sourceSets.test.allSource.srcDirs)
    auxiliaryClasspath.setFrom(sourceSets.test.compileClasspath)
}

tasks.withType(Checkstyle).configureEach {
    reports {
        xml.required = true
        html.required = true
        html.outputLocation = file("$buildDir/reports/checkstyle/${name}.html")
    }
}
