import type {
  UserDto,
  LobbyDto,
  TaskDto,
  EventDto,
  FreeSlotDto,
  LobbyInviteDto,
  NotificationDto,
} from '@/types';

export const MOCK_USERS: UserDto[] = [
  {
    id: 1,
    username: 'alex_johnson',
    email: 'alex@lined.app',
    createdAt: '2025-01-15T10:00:00Z',
    roles: ['ROLE_USER'],
    activePlan: 'PRO_MONTHLY',
    activeUntil: '2026-05-15T10:00:00Z',
  },
  {
    id: 2,
    username: 'nastia_k',
    email: 'anastasiia@lined.app',
    createdAt: '2025-02-01T12:00:00Z',
    roles: ['ROLE_USER'],
    activePlan: 'PRO_MONTHLY',
    activeUntil: '2026-05-01T12:00:00Z',
  },
  {
    id: 3,
    username: 'nastia_bondar',
    email: 'nastia.bondar@lined.app',
    createdAt: '2025-06-10T09:00:00Z',
    roles: ['ROLE_USER'],
    activePlan: null,
    activeUntil: null,
  },
  {
    id: 4,
    username: 'natascha_m',
    email: 'natascha@lined.app',
    createdAt: '2025-08-22T09:00:00Z',
    roles: ['ROLE_USER'],
    activePlan: null,
    activeUntil: null,
  },
  {
    id: 5,
    username: 'maria_garcia',
    email: 'maria@lined.app',
    createdAt: '2025-09-03T10:00:00Z',
    roles: ['ROLE_USER'],
    activePlan: 'PRO_MONTHLY',
    activeUntil: '2026-06-03T10:00:00Z',
  },
  {
    id: 6,
    username: 'james_lee',
    email: 'james@lined.app',
    createdAt: '2025-09-15T14:00:00Z',
    roles: ['ROLE_USER'],
    activePlan: null,
    activeUntil: null,
  },
  {
    id: 7,
    username: 'sophia_chen',
    email: 'sophia@lined.app',
    createdAt: '2025-10-01T09:00:00Z',
    roles: ['ROLE_USER'],
    activePlan: null,
    activeUntil: null,
  },
  {
    id: 8,
    username: 'ryan_patel',
    email: 'ryan@lined.app',
    createdAt: '2025-10-20T11:00:00Z',
    roles: ['ROLE_USER'],
    activePlan: 'PRO_MONTHLY',
    activeUntil: '2026-07-20T11:00:00Z',
  },
];

export const MOCK_LOBBIES: LobbyDto[] = [
  {
    id: 1,
    name: 'Alex & Anastasiia',
    lobbyType: 'COUPLE',
    ownerId: 1,
    memberIds: [1, 2],
  },
  {
    id: 2,
    name: 'Johnson Family',
    lobbyType: 'FAMILY',
    ownerId: 1,
    memberIds: [1, 2],
  },
  {
    id: 3,
    name: 'Weekend Crew',
    lobbyType: 'FRIENDS',
    ownerId: 1,
    memberIds: [1, 2],
  },
  {
    id: 4,
    name: 'Design Team',
    lobbyType: 'WORK',
    ownerId: 1,
    memberIds: [1, 5, 6, 7],
  },
];

const today = new Date();
const todayStr = today.toISOString().slice(0, 10);
const tomorrow = new Date(today);
tomorrow.setDate(tomorrow.getDate() + 1);
const tomorrowStr = tomorrow.toISOString().slice(0, 10);
const dayAfter = new Date(today);
dayAfter.setDate(dayAfter.getDate() + 2);
const dayAfterStr = dayAfter.toISOString().slice(0, 10);
const inThreeDaysStr = new Date(today.getTime() + 3 * 24 * 60 * 60 * 1000)
  .toISOString()
  .slice(0, 10);
const inFourDaysStr = new Date(today.getTime() + 4 * 24 * 60 * 60 * 1000)
  .toISOString()
  .slice(0, 10);
const inTenDaysStr = new Date(today.getTime() + 10 * 24 * 60 * 60 * 1000)
  .toISOString()
  .slice(0, 10);
const yesterdayStr = new Date(today.getTime() - 24 * 60 * 60 * 1000)
  .toISOString()
  .slice(0, 10);
const dayAfterPlusOneStr = new Date(dayAfter.getTime() + 24 * 60 * 60 * 1000)
  .toISOString()
  .slice(0, 10);

/** A 3h mutual free window a few days out, used by the dashboard free-slot banner. */
export const MOCK_FREE_SLOT: FreeSlotDto = {
  start: `${inThreeDaysStr}T14:00:00Z`,
  end: `${inThreeDaysStr}T17:00:00Z`,
};

export const MOCK_TASKS: TaskDto[] = [
  {
    id: 1,
    title: 'Plan dinner for Saturday',
    description: 'Pick a restaurant and book a table for two',
    priority: 'MEDIUM',
    status: 'TODO',
    lobbyId: 1,
    creatorId: 1,
    assigneeId: 1,
    dueDate: tomorrowStr,
    createdAt: '2026-04-09T08:00:00Z',
  },
  {
    id: 2,
    title: 'Book restaurant reservation',
    description: null,
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    lobbyId: 1,
    creatorId: 2,
    assigneeId: 1,
    dueDate: todayStr,
    createdAt: '2026-04-08T14:00:00Z',
  },
  {
    id: 3,
    title: 'Buy groceries',
    description: 'Milk, bread, eggs',
    priority: 'LOW',
    status: 'DONE',
    lobbyId: 2,
    creatorId: 1,
    assigneeId: 2,
    dueDate: todayStr,
    createdAt: '2026-04-07T09:00:00Z',
  },
  {
    id: 4,
    title: 'Prepare presentation slides',
    description: null,
    priority: 'MEDIUM',
    status: 'TODO',
    lobbyId: 3,
    creatorId: 1,
    assigneeId: 1,
    dueDate: dayAfterStr,
    createdAt: '2026-04-10T10:00:00Z',
  },
  {
    id: 5,
    title: 'Send invitations',
    description: null,
    priority: 'MEDIUM',
    status: 'IN_PROGRESS',
    lobbyId: 3,
    creatorId: 2,
    assigneeId: 2,
    dueDate: tomorrowStr,
    createdAt: '2026-04-09T16:00:00Z',
  },
  {
    id: 6,
    title: 'Clean apartment',
    description: null,
    priority: 'LOW',
    status: 'TODO',
    lobbyId: 2,
    creatorId: 1,
    assigneeId: null,
    dueDate: null,
    createdAt: '2026-04-10T11:00:00Z',
  },
  {
    id: 7,
    title: 'Finalize onboarding flow mockups',
    description: 'Incorporate feedback from the last design review',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    lobbyId: 4,
    creatorId: 1,
    assigneeId: 5,
    dueDate: tomorrowStr,
    createdAt: '2026-04-11T09:00:00Z',
  },
  {
    id: 8,
    title: 'Review pull requests',
    description: null,
    priority: 'MEDIUM',
    status: 'TODO',
    lobbyId: 4,
    creatorId: 1,
    assigneeId: 6,
    dueDate: todayStr,
    createdAt: '2026-04-11T10:00:00Z',
  },
  {
    id: 9,
    title: 'Submit expense report',
    description: 'Overdue since last week',
    priority: 'MEDIUM',
    status: 'TODO',
    lobbyId: 4,
    creatorId: 7,
    assigneeId: 7,
    dueDate: yesterdayStr,
    createdAt: '2026-04-05T08:00:00Z',
  },
  {
    id: 10,
    title: 'Prepare quarterly roadmap deck',
    description: null,
    priority: 'HIGH',
    status: 'TODO',
    lobbyId: 4,
    creatorId: 1,
    assigneeId: 1,
    dueDate: inTenDaysStr,
    createdAt: '2026-04-11T12:00:00Z',
  },
  {
    id: 11,
    title: 'Water the plants',
    description: null,
    priority: 'LOW',
    status: 'DONE',
    lobbyId: 1,
    creatorId: 2,
    assigneeId: 2,
    dueDate: yesterdayStr,
    createdAt: '2026-04-06T08:00:00Z',
  },
];

export const MOCK_EVENTS: EventDto[] = [
  {
    id: 1,
    title: 'Morning Coffee',
    location: 'Blue Bottle Cafe',
    shared: true,
    startAt: `${todayStr}T09:00:00Z`,
    endAt: `${todayStr}T10:00:00Z`,
    timezone: 'UTC',
    lobbyId: 1,
    ownerId: 1,
    createdAt: '2026-04-08T08:00:00Z',
  },
  {
    id: 2,
    title: 'Team Lunch',
    location: null,
    shared: true,
    startAt: `${todayStr}T12:00:00Z`,
    endAt: `${todayStr}T13:00:00Z`,
    timezone: 'UTC',
    lobbyId: 3,
    ownerId: 1,
    createdAt: '2026-04-07T10:00:00Z',
  },
  {
    id: 3,
    title: 'Family Dinner',
    location: 'Home',
    shared: true,
    startAt: `${tomorrowStr}T18:00:00Z`,
    endAt: `${tomorrowStr}T20:00:00Z`,
    timezone: 'UTC',
    lobbyId: 2,
    ownerId: 1,
    createdAt: '2026-04-09T09:00:00Z',
  },
  {
    id: 4,
    title: 'Movie Night',
    location: null,
    shared: true,
    startAt: `${tomorrowStr}T20:30:00Z`,
    endAt: `${tomorrowStr}T23:00:00Z`,
    timezone: 'UTC',
    lobbyId: 1,
    ownerId: 2,
    createdAt: '2026-04-09T11:00:00Z',
  },
  {
    id: 5,
    title: 'Weekend Hike',
    location: 'Blue Ridge Trailhead',
    shared: true,
    startAt: `${dayAfterStr}T08:00:00Z`,
    endAt: `${dayAfterStr}T12:00:00Z`,
    timezone: 'UTC',
    lobbyId: 3,
    ownerId: 1,
    createdAt: '2026-04-10T07:00:00Z',
  },
  {
    id: 6,
    title: 'Morning Run',
    location: 'Riverside Park',
    shared: true,
    startAt: `${todayStr}T06:00:00Z`,
    endAt: `${todayStr}T07:00:00Z`,
    timezone: 'UTC',
    lobbyId: 1,
    ownerId: 1,
    createdAt: '2026-04-11T06:00:00Z',
  },
  {
    id: 7,
    title: 'Design Standup',
    location: null,
    shared: true,
    startAt: `${todayStr}T15:00:00Z`,
    endAt: `${todayStr}T15:30:00Z`,
    timezone: 'UTC',
    lobbyId: 4,
    ownerId: 1,
    createdAt: '2026-04-11T07:00:00Z',
  },
  {
    id: 8,
    // Deliberately overlaps "Team Lunch" (lobby 3, same day, 12:00-13:00) by
    // 30 minutes across two different lobbies -- exercises side-by-side lane
    // layout and the lobby-visibility filter on the global calendar.
    title: 'Design Sync',
    location: null,
    shared: true,
    startAt: `${todayStr}T12:30:00Z`,
    endAt: `${todayStr}T13:30:00Z`,
    timezone: 'UTC',
    lobbyId: 4,
    ownerId: 1,
    createdAt: '2026-04-11T07:15:00Z',
  },
  {
    id: 9,
    title: '1:1 with Manager',
    location: null,
    shared: true,
    startAt: `${tomorrowStr}T14:00:00Z`,
    endAt: `${tomorrowStr}T14:30:00Z`,
    timezone: 'UTC',
    lobbyId: 4,
    ownerId: 1,
    createdAt: '2026-04-11T07:30:00Z',
  },
  {
    id: 10,
    // A second midnight-spanning event (different lobby than "Movie Night")
    // -- regression coverage for the day-column clipping/split rendering.
    title: 'Family Game Night',
    location: 'Home',
    shared: true,
    startAt: `${dayAfterStr}T22:00:00Z`,
    endAt: `${dayAfterPlusOneStr}T01:00:00Z`,
    timezone: 'UTC',
    lobbyId: 2,
    ownerId: 1,
    createdAt: '2026-04-10T08:00:00Z',
  },
  {
    id: 11,
    title: 'Design Team Offsite',
    location: 'Lakeside Retreat Center',
    shared: true,
    startAt: `${dayAfterStr}T08:00:00Z`,
    endAt: `${dayAfterStr}T20:00:00Z`,
    timezone: 'UTC',
    lobbyId: 4,
    ownerId: 1,
    createdAt: '2026-04-10T09:00:00Z',
  },
  {
    id: 12,
    title: 'Quarterly Roadmap Review',
    location: null,
    shared: true,
    startAt: `${inTenDaysStr}T16:00:00Z`,
    endAt: `${inTenDaysStr}T17:30:00Z`,
    timezone: 'UTC',
    lobbyId: 4,
    ownerId: 1,
    createdAt: '2026-04-11T08:00:00Z',
  },
  {
    id: 13,
    title: 'Anniversary Dinner',
    location: 'Le Petit Bistro',
    shared: true,
    startAt: `${inFourDaysStr}T19:00:00Z`,
    endAt: `${inFourDaysStr}T21:00:00Z`,
    timezone: 'UTC',
    lobbyId: 1,
    ownerId: 2,
    createdAt: '2026-04-10T10:00:00Z',
  },
];

export const MOCK_LOBBY_INVITES: LobbyInviteDto[] = [
  {
    id: 1,
    lobbyId: 3,
    inviterId: 1,
    inviteeId: 2,
    status: 'PENDING',
    sentAt: '2026-07-15T10:00:00Z',
    createdAt: '2026-07-15T10:00:00Z',
    updatedAt: '2026-07-15T10:00:00Z',
  },
  {
    id: 2,
    lobbyId: 1,
    inviterId: 1,
    inviteeId: 3,
    status: 'PENDING',
    sentAt: '2026-03-27T10:00:00Z',
    createdAt: '2026-03-27T10:00:00Z',
    updatedAt: '2026-03-27T10:00:00Z',
  },
  {
    id: 3,
    lobbyId: 4,
    inviterId: 1,
    inviteeId: 8,
    status: 'PENDING',
    sentAt: '2026-07-16T09:00:00Z',
    createdAt: '2026-07-16T09:00:00Z',
    updatedAt: '2026-07-16T09:00:00Z',
  },
];

export const MOCK_NOTIFICATIONS: NotificationDto[] = [
  {
    id: 1,
    type: 'TASK_ASSIGNED',
    title: 'New task assigned',
    message: 'You were assigned "Plan dinner for Saturday"',
    lobbyId: 1,
    taskId: 1,
    eventId: null,
    readAt: null,
    createdAt: '2026-07-15T09:00:00Z',
    deliveries: [
      {
        channel: 'IN_APP',
        status: 'DELIVERED',
        queuedAt: '2026-07-15T09:00:00Z',
        deliveredAt: '2026-07-15T09:00:00Z',
      },
      {
        channel: 'EMAIL',
        status: 'PENDING',
        queuedAt: '2026-07-15T09:00:00Z',
        deliveredAt: null,
      },
    ],
  },
  {
    id: 2,
    type: 'SHARED_EVENT_CREATED',
    title: 'New shared event',
    message: '"Family Dinner" was added to Johnson Family',
    lobbyId: 2,
    taskId: null,
    eventId: 3,
    readAt: '2026-07-15T12:00:00Z',
    createdAt: '2026-07-15T11:00:00Z',
    deliveries: [
      {
        channel: 'IN_APP',
        status: 'DELIVERED',
        queuedAt: '2026-07-15T11:00:00Z',
        deliveredAt: '2026-07-15T11:00:00Z',
      },
    ],
  },
  {
    id: 3,
    type: 'TASK_ASSIGNED',
    title: 'New task assigned',
    message: 'You were assigned "Prepare quarterly roadmap deck"',
    lobbyId: 4,
    taskId: 10,
    eventId: null,
    readAt: null,
    createdAt: '2026-07-16T08:00:00Z',
    deliveries: [
      {
        channel: 'IN_APP',
        status: 'DELIVERED',
        queuedAt: '2026-07-16T08:00:00Z',
        deliveredAt: '2026-07-16T08:00:00Z',
      },
    ],
  },
];
