name: CI backend pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/lined

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Run static checks (Checkstyle + SpotBugs + Tests)
        run: ./gradlew check

      - name: Generate code coverage report
        run: ./gradlew jacocoTestReport

      - name: Build and analyze with SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonarqube --info -Dsonar.login=$SONAR_TOKEN

      - name: Generate SpotBugs XML
        run: ./gradlew spotbugsMain

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Annotate SpotBugs with reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            cat build/reports/spotbugs/main.xml | reviewdog -f=checkstyle \
              -name="spotbugs" \
              -reporter=github-pr-review \
              -filter-mode=added \
              -fail-on-error=false

      - name: Annotate Checkstyle
        uses: dbelyaev/action-checkstyle@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          checkstyle_config: backend/lined/config/checkstyle/checkstyle.xml
          workdir: backend/lined
          reporter: github-pr-review