apiVersion: v1
kind: Secret
metadata:
  name: lined-postgres
  labels:
    app.kubernetes.io/name: lined-postgres
    app.kubernetes.io/part-of: lined
type: Opaque
stringData:
  username: postgres
  password: postgres
  database: lineddb
